---
title: "SDS 237 - Mini-Project: Infrastructural Analysis Annotated Bibliography"
author: "YOUR NAME HERE"
date: "Last updated on `r Sys.Date()`"
output: pdf_document
bibliography: infrastructural-analysis.bib
csl: ../../resources/chicago-author-date.csl
---

> Complete your annotated bibliography below. 

1. A short history of GDP: moving towards better measures of human well-being

This article briefly introduces the history of GDP invention and how European countries in the International Monetary Fund(IMF) play an important role in shaping its measure methodology. It also points out that GDP is an inaccurate measurement of human well-being since it is based on an incomplete picture of the system within which the human economy operates. 

@article{costanza2014short,
  title={A short history of GDP: moving towards better measures of human well-being},
  author={Costanza, Robert and Hart, Maureen and Kubiszewski, Ida and Talberth, John and others},
  journal={Solutions},
  volume={5},
  number={1},
  pages={91--97},
  year={2014}
}


2. The Long Twentieth Century: Money, Power, and the Origins of Our Times, London: Verso.

This paper explains the Peace of Westphalia and how England and France gradually rose to dominant positions through a series of wars and the formation of nation-states in Europe.

@book{arrighi1994long,
  title={The long twentieth century: Money, power, and the origins of our times},
  author={Arrighi, Giovanni},
  year={1994},
  publisher={verso}
}


3. Gross Domestic Power: A History of GDP as Numerical Rhetoric

The paper explains the usually overlooked part of GDP’s history around the 17th century, providing evidence that the creation of GDP was politically motivated and often utilized as a political weapon.

@article{assa2019gross,
  title={Gross Domestic Power: A History of GDP as Numerical Rhetoric},
  author={Assa, Jacob},
  journal={Annali della Fondazione Luigi Einaudi},
  volume={53},
  pages={81--96},
  year={2019},
  publisher={Casa Editrice Leo S. Olschki}
}


4. Doughnut economics: seven ways to think like a 21st-century economist

It reflects on the flaw of the current economic model, such as not counting women’s work in the household as part of GDP, encouraging unsustainable ways of developing the economy at the expense of natural resources.

@book{raworth2017doughnut,
  title={Doughnut economics: seven ways to think like a 21st-century economist},
  author={Raworth, Kate},
  year={2017},
  publisher={Chelsea Green Publishing}
}



5. Imputing away the ladder: Implications of changes in national accounting standards for assessing inter-country inequalities

This article talks about how the U.S changes System of Nation Account, redefining the yardstick of development to fit recent strengths of advanced economies. Thus the gap between developing countries and Western countries becomes even greater.

@article{assa2018imputing,
  title={Imputing away the ladder: Implications of changes in national accounting standards for assessing inter-country inequalities},
  author={Assa, Jacob and Kvangraven, Ingrid H and others},
  journal={ESRC GPID Research Network Working Paper},
  volume={14},
  year={2018}
}


