---
title: "SDS 237 - Mini-Project: Interview"
author: "YOUR NAME HERE"
date: "Last updated on `r Sys.Date()`"
output: pdf_document
bibliography: interview.bib
csl: ../../resources/chicago-author-date.csl
---

> Compose your write-up below.

This memo is based on an interview with Tuwan, an ethnographer currently working as a market researcher at a consulting firm in China.

Ethnography is a method that mainly collects qualitative data, providing more nuanced explanation than ordinary quantitative studies do. Recording, organizing, understanding, and interpreting qualitative data may be even more strenuous than quantitative research, but people don’t usually realize it. In commercial settings, ethnography is also useful, which is often used for qualitative market and customer research.
Literally, ethnography simply means to write about people. But it is not strictly applied  anymore, according to Tuwan. Ethnography now is a bundle of methods that is used to investigate people in different parts of societies and cultures, such as watching what people do, asking questions, participating in what people do, which might involve interviewing, actually going for walks with people. In Tuwan’s past ethnographic research experiences, she had taken photographs of people, recorded videos, and even asked people to record or photograph aspects of their life. 

Compared to other disciplines that studies humans in a controlled environment, collecting mostly quantitative data, ethnography is an approach to researching with people, trying to understand their world, participating in their worlds. It doesn't involve studying people as if the researchers are separate from them. It is studying people within a relationship with them, participating in and collaborating with them to produce new ways of understanding, Tuwan explained. Because the way ethnography engages with its participants, it is a cardinal method for delving beneath the surface, comprehending the things we would normally never see people doing in their everyday life. For instance, in some of her studies, she looked at people’s everyday morning routines from when they get up and get out of bed, and what they did when they left the house. These data collected by ethnographic method reveal the very mundane aspects of everyday life that people would never bring up in a formal interview or quantitative survey. It can be even said to be deliberately subjective, because when doing ethnography research, researchers essentially try to connect their own experiences to those of others using forms of empathy or imagination. Admittedly, it is impossible to know what it's like to be somebody else, but ethnographers try to get close in the most respectful way possible. 

Tuwan provided a really interesting parallel in Geography. Human geographers are oftentimes critical of maps because maps flatten out things, transforming 3D objects to 2D. Mapping takes a slice across the world and looks at it from above as opposed to the normal geographers who love 2D maps. However, movement is heavily emphasized in human geography. The concept of movement is about “going through”. It enables us to understand life as it progresses through the paths that life takes and how it meanders through the environment. It’s important to understand what happens when people start to “move through” an environment, what do they sense, what do they feel and what do they pick up, and that’s what ethnography enables us to do.

Tuwan did mention that ethnography can be used in many different disciplines, such as sociology, anthropology, and even human-computer interaction. As a method, ethnography could be changed by the way that it was shaped by the disciplines which it was being used at the time. Consequently, there was always a different inflection in the way that ethnography is practice in relation to the academic and scholarly discipline.

In commercial settings, an ethnographic approach is adopted to provide a more nuanced understanding of potential customers’ values and preferences, thus informing companies about their consumption behavior. For example, when Tuwan was doing customer studies for a cosmetics company, she would go to their houses and ask the participants to show their skin care routine, and asked them how they determine what is a good product. They even asked participants to observe their images in the mirror, and point out any signs of aging they’ve discovered on their face, which is a brutal process. As part of Tuwan’s job, she also is in charge of observing macro-level cultural trends by doing daily logs of news or incidents that reach a certain popularity threshold, interpreting and labeling them into different categories. At the end of each month, she would do thematic analysis about incidents under each category. By the end of the year, she would have a list of various themes that come up during the year, and the recurring themes become their ethnographic research topic. 

Ethnography research is a different way of collecting and engaging with data. It seeks to “move through” the environment, taking context into consideration, instead of observing from above as most qualitative studies do. It provides researchers with tools to delve deeper into phenomena, interpret data in a brand new way.


